name: Run tests

on: [pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Import required modules
      run: Install-Module -Name Pester -Force
      shell: pwsh
    - name: Run tests
      run: .\Tests\TestRunner.ps1 -TestResults -Verbosity Normal -CodeCoverage
      shell: pwsh
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      continue-on-error: true
      with:
        files: testResults.xml
